### ISSUE TITLE
Error formatting WFS 2.0 test results

### ISSUE THREAD

**Issue by jill7072** [opengeospatial/ets-wfs20#142]
I am running the team engine tests for WFS 2.0 and I'm finding that the test results are properly formatted for some of my URLs but I'm receiving an error for other URLs. This is reproducible on the 1.26 version as well as the beta site (1.30).
![image](https://user-images.githubusercontent.com/19600343/51870173-b03c5d00-2307-11e9-8161-bba03a5a64a5.png)

When I click to view the old test report I get the following message:

> Test tns:Main type Mandatory default result Passed (s0002)
> 
> Assertion: The test subject satisfies all applicable constraints.
> 
> Form d1e46_1:
>    fid=
>    wfs-uri=https://ogccert.dev.geocloud.com:6443/arcgis/services/cite_wfs_200_T/MapServer/WFSServer?service=WFS&version=2.0.0&request=GetCapabilities
> 
> Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.iso19142.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.RuntimeException: Failed to parse resource located at https://ogccert.dev.geocloud.com:6443/arcgis/services/cite_wfs_200_T/MapServer/WFSServer?service=WFS&version=2.0.0&request=GetCapabilities
> Result: Failed

I have a temporary URL that reproduces the error:
https://ogccert.dev.geocloud.com:6443/arcgis/services/cite_wfs_200_T/MapServer/WFSServer?service=WFS&version=2.0.0&request=GetCapabilities

This issue was moved from: https://github.com/opengeospatial/teamengine/issues/387

**Comment by dstenger** [comment]
Thank you for moving the issue.
@keshav-nangare Can you please analyse why this error is occurring?

**Comment by keshav-nangare** [comment]
@dstenger 

This issue is related to SSL certificate.

```
Caused by: java.lang.RuntimeException: Failed to parse resource located at https://ogccert.dev.geocloud.com:6443/arcgis/services/cite_wfs_200_T/MapServer/WFSServer?service=WFS&version=2.0.0&request=GetCapabilities
	at org.opengis.cite.iso19142.SuiteFixtureListener.processWfsParameter(SuiteFixtureListener.java:91)
	at org.opengis.cite.iso19142.SuiteFixtureListener.onStart(SuiteFixtureListener.java:47)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:208)
	at org.testng.SuiteRunner.run(SuiteRunner.java:266)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:130)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
	at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
	... 49 more
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:177)
	at org.opengis.cite.iso19142.util.URIUtils.resolveURIAsDocument(URIUtils.java:59)
	at org.opengis.cite.iso19142.SuiteFixtureListener.processWfsParameter(SuiteFixtureListener.java:82)
	... 66 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 88 more
```


This is similar to : https://github.com/opengeospatial/ets-wfs20/issues/99#issuecomment-372356434

**Comment by dstenger** [comment]
So, the service cannot be validated because the certificate is self signed (error message: unable to find valid certification path to requested target).
TEAM Engine does not accept self signed certificates.

@jill7072
Can you please try to use a non-self signed certificate or disable TLS for testing purposes?

**Comment by jill7072** [comment]
Thanks, @dstenger I didn't realize that TEAM engine did not accept self-signed certificates. I tried with a new service and the formatting of the results worked as expected. Thank you!
