### ISSUE TITLE
Failed to connect to the EPSG database

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs20#17]
Running locally the final report just says everything PASSED, but also that all tests were skipped (89 of them), a  EPSG db initialization errors shown. What is the issue?

```
[exec] Cannot create JDBC driver of class '' for connect URL 'null'
     [exec] org.opengis.util.FactoryException: Failed to connect to the EPSG database.
     [exec] at org.geotoolkit.referencing.factory.epsg.ThreadedEpsgFactory.createBackingStore(ThreadedEpsgFactory.java:678)
     [exec] at org.geotoolkit.referencing.factory.ThreadedAuthorityFactory.getBackingStore(ThreadedAuthorityFactory.java:372)
     [exec] at org.geotoolkit.referencing.factory.CachingAuthorityFactory.availability(CachingAuthorityFactory.java:296)
     [exec] at org.geotoolkit.factory.FactoryRegistry.isAcceptable(FactoryRegistry.java:579)
     [exec] at org.geotoolkit.factory.FactoryRegistry$1.filter(FactoryRegistry.java:237)
     [exec] at javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:810)
     [exec] at javax.imageio.spi.FilterIterator.next(ServiceRegistry.java:828)
     [exec] at org.geotoolkit.internal.LazySet.addNext(LazySet.java:77)
     [exec] at org.geotoolkit.internal.LazySet.size(LazySet.java:96)
     [exec] at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
     [exec] at java.util.ArrayList.<init>(ArrayList.java:164)
     [exec] at org.geotoolkit.referencing.DefaultAuthorityFactory.create(DefaultAuthorityFactory.java:111)
     [exec] at org.geotoolkit.referencing.CRS.getAuthorityFactory(CRS.java:227)
     [exec] at org.geotoolkit.referencing.CRS.decode(CRS.java:434)
     [exec] at org.opengis.cite.iso19142.FeatureTypeInfo.setDefaultCRS(FeatureTypeInfo.java:89)
     [exec] at org.opengis.cite.iso19142.util.ServiceMetadataUtils.extractFeatureInfo(ServiceMetadataUtils.java:194)
     [exec] at org.opengis.cite.iso19142.SuiteFixtureListener.processWfsParameter(SuiteFixtureListener.java:92)
     [exec] at org.opengis.cite.iso19142.SuiteFixtureListener.onStart(SuiteFixtureListener.java:40)
     [exec] at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:199)
     [exec] at org.testng.SuiteRunner.run(SuiteRunner.java:252)
     [exec] at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
     [exec] at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
     [exec] at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
     [exec] at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
     [exec] at org.testng.TestNG.run(TestNG.java:1057)
     [exec] at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:115)
     [exec] at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:119)
     [exec] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [exec] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] at java.lang.reflect.Method.invoke(Method.java:606)
     [exec] at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
     [exec] at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
     [exec] at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
     [exec] at net.sf.saxon.instruct.CopyOf.processLeavingTail(CopyOf.java:292)
     [exec] at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
     [exec] at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
     [exec] at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
     [exec] at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
     [exec] at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
     [exec] at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
     [exec] at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
     [exec] at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
     [exec] at net.sf.saxon.Controller.transform(Controller.java:1560)
     [exec] at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
     [exec] at com.occamlab.te.TECore.executeTemplate(TECore.java:571)
     [exec] at com.occamlab.te.TECore.executeXSLFunction(TECore.java:1034)
     [exec] at com.occamlab.te.TECore.callFunction(TECore.java:1066)
     [exec] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [exec] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] at java.lang.reflect.Method.invoke(Method.java:606)
     [exec] at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
     [exec] at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
     [exec] at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
     [exec] at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:352)
     [exec] at net.sf.saxon.expr.Expression.process(Expression.java:461)
     [exec] at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:282)
     [exec] at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
     [exec] at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
     [exec] at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:542)
     [exec] at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
     [exec] at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
     [exec] at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
     [exec] at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
     [exec] at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
     [exec] at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
     [exec] at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
     [exec] at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
     [exec] at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
     [exec] at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
     [exec] at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
     [exec] at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
     [exec] at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
     [exec] at net.sf.saxon.Controller.transform(Controller.java:1560)
     [exec] at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
     [exec] at com.occamlab.te.TECore.executeTemplate(TECore.java:571)
     [exec] at com.occamlab.te.TECore.executeTest(TECore.java:779)
     [exec] at com.occamlab.te.TECore.execute_test(TECore.java:390)
     [exec] at com.occamlab.te.TECore.execute_suite(TECore.java:438)
     [exec] at com.occamlab.te.TECore.execute(TECore.java:295)
     [exec] at com.occamlab.te.TECore.run(TECore.java:2273)
     [exec] at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL 'null'
     [exec] at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1452)
     [exec] at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
     [exec] at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
     [exec] at org.geotoolkit.referencing.factory.epsg.ThreadedEpsgFactory.createBackingStore(ThreadedEpsgFactory.java:565)
     [exec] at org.geotoolkit.referencing.factory.epsg.ThreadedEpsgFactory.createBackingStore(ThreadedEpsgFactory.java:652)
     [exec] ... 82 more
     [exec] Caused by: java.lang.NullPointerException
     [exec] at sun.jdbc.odbc.JdbcOdbcDriver.getProtocol(JdbcOdbcDriver.java:524)
     [exec] at sun.jdbc.odbc.JdbcOdbcDriver.knownURL(JdbcOdbcDriver.java:493)
     [exec] at sun.jdbc.odbc.JdbcOdbcDriver.acceptsURL(JdbcOdbcDriver.java:307)
     [exec] at java.sql.DriverManager.getDriver(DriverManager.java:262)
     [exec] at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1437)
     [exec] ... 86 more
     [exec] 
```

**Comment by rjmartell** [comment]
The `derby-10.*.jar` file needs to be on the classpath. When run via the web app (which seems to be the case here), it must be available to the common classloader (in CATALINA_BASE/lib) and **not** in WEB-INF/lib.

Note that the EPSG database should be automatically created if it doesn't already exist. The system property `-Dderby.system.home` should refer to the Derby system directory that contains the database (in EPSG/7.09).
