### ISSUE TITLE
Support for "application/zip" accepted mediatype

### ISSUE THREAD

**Issue by jyrkka** [opengeospatial/ets-wfs20#205]
Currently suite is not supporting "application/zip" as the result type. The reason is the quite old version of the teamengine-spi dependency. 

Would it be possible to bump up the version? The reason I would like to have this is because it would generate the result as html which is more human readable that the earl or xml report.

**Comment by dstenger** [comment]
Thank you for reporting.

Are you referencing the REST interface of TEAM Engine?
This functionality is provided by the TEAM Engine software and not the implementation of the test suite. Thus, it should be possible to retrieve application/zip via the REST interface when the latest version of TEAM Engine is used.

However, of course, teamengine-spi dependency can be updated to the latest version. Currently, the version is retrieved from ets-common (https://github.com/opengeospatial/ets-common). I propose to set the version in the pom file of this test suite directly.

**Comment by jyrkka** [comment]
@dstenger that folder has full access for everyone.

drwxrwxrwx  5 jyrkka xxx xxx       4096 Oct 11 16:41 teamengine

Do you want me to check it some other way?

**Comment by jyrkka** [comment]
Just tested folder permission by modifying the test suite to write some random file to that folder and suite was able to write that file. So I guess it is not because of those folder permissions.

**Comment by dstenger** [comment]
Thank you, we will do further investigation.

**Comment by dstenger** [comment]
I also updated the dependency by adding following to the pom:
```
    <dependency>
      <groupId>org.opengis.cite.teamengine</groupId>
      <artifactId>teamengine-spi</artifactId>
      <version>5.4.1</version>
    </dependency>
```

Although, the tests are run, I am getting following exceptions:
```
...
INFORMATION: Using outputDirPath: /home/stenger
java.io.FileNotFoundException: /home/stenger/teamengine/config.xml (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at com.occamlab.te.vocabulary.Config.<init>(Config.java:73)
	at com.occamlab.te.spi.executors.testng.EarlReporter.<init>(EarlReporter.java:95)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:965)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:914)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:137)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)
...
[TestNG] Reporter com.occamlab.te.spi.executors.testng.EarlReporter@c8e4bb0 failed
java.lang.NullPointerException
	at com.occamlab.te.spi.executors.testng.EarlReporter.isBasicConformanceClass(EarlReporter.java:451)
	at com.occamlab.te.spi.executors.testng.EarlReporter.addTestRequirements(EarlReporter.java:240)
	at com.occamlab.te.spi.executors.testng.EarlReporter.generateReport(EarlReporter.java:103)
	at org.testng.TestNG.generateReports(TestNG.java:1135)
	at org.testng.TestNG.run(TestNG.java:1081)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:137)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)
...
```

These are the same exceptions as reported above.

However, the report is still generated:
```
...
Test results: file:/home/stenger/testng/c3b6646e-57c5-4e9d-8351-0dc13e7c5af2/testng-results.xml
...
ls /home/stenger/testng/c3b6646e-57c5-4e9d-8351-0dc13e7c5af2/
testng-results.xml
```

Thus, now, just the testng-results.xml file is existing (filled correctly).

We have to re-evaluate the aio.jar and check why the earl and zip reports are not generated.
Most likely, the aio.jar functionality has never been tested with teamengine-spi v5.4.1.

**Comment by bpross-52n** [comment]
@jyrkka I tested enabling the generation of additional reports, which leads to the following output:

![generated-reports](https://user-images.githubusercontent.com/3692794/143196834-9f3e39ae-d067-4bd9-9571-9bcf8c918743.png)

HTML reports are also generated:

![html-report](https://user-images.githubusercontent.com/3692794/143196993-20a1ab25-328d-4f4c-a4fb-313ad8d81088.png)

Would this be helpful for you?

**Comment by jyrkka** [comment]
@bpross-52n That is better than nothing, but for example for wmts-10 testsuite we get slightly better html report (in my opinion).

![image](https://user-images.githubusercontent.com/17827509/143437519-f45ec513-854c-4f1e-a9bf-c8bd63f75c66.png)

We also get quite good details of the failure.

![image](https://user-images.githubusercontent.com/17827509/143437811-047edcf0-9838-490e-93a5-f1403233c41a.png)

Would it be possible to get that type html report from this suite as well?

**Comment by bpross-52n** [comment]
@jyrkka I have updated the Teamengine dependency and added a property to the test-run-props.xml. Now the CITE HTML reports  are generated again. You can use the following branch for testing: https://github.com/opengeospatial/ets-wfs20/tree/issue%23205 Note that there is a known issue with the generation of the zip file.

**Comment by dstenger** [comment]
@bpross-52n 
When I am running the jar by using https://github.com/opengeospatial/ets-wfs20/blob/dd77f2b3fd1b52dd24ff5f4d5d7cf87f908a00d3/src/main/resources/test-run-props.xml and following command
```
stenger@elsbeere:~/git/ets-wfs20/target$ java -jar ets-wfs20-1.37-SNAPSHOT-aio.jar test-run-props.xml
```
errors are returned and no HTML report is generated:
```
[TestNG] Reporter com.occamlab.te.spi.executors.testng.EarlReporter@c8e4bb0 failed
java.lang.NullPointerException
	at com.occamlab.te.spi.executors.testng.EarlReporter.isBasicConformanceClass(EarlReporter.java:451)
	at com.occamlab.te.spi.executors.testng.EarlReporter.addTestRequirements(EarlReporter.java:240)
	at com.occamlab.te.spi.executors.testng.EarlReporter.generateReport(EarlReporter.java:103)
	at org.testng.TestNG.generateReports(TestNG.java:1135)
	at org.testng.TestNG.run(TestNG.java:1081)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:137)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)
Error 
  java.io.FileNotFoundException:
  /home/stenger/testng/e9b58970-67d6-4b70-970d-281b649ec403/earl-results.rdf (Datei oder
  Verzeichnis nicht gefunden)
Jan 20, 2022 9:11:13 PM com.occamlab.te.spi.util.HtmlReport earlHtmlReport
SCHWERWIEGEND: Transformation of EARL to HTML failed.
net.sf.saxon.trans.XPathException: java.io.FileNotFoundException: /home/stenger/testng/e9b58970-67d6-4b70-970d-281b649ec403/earl-results.rdf (Datei oder Verzeichnis nicht gefunden)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:384)
	at net.sf.saxon.event.Sender.send(Sender.java:185)
	at net.sf.saxon.event.Sender.send(Sender.java:49)
	at net.sf.saxon.Controller.transform(Controller.java:1550)
	at com.occamlab.te.spi.util.HtmlReport.earlHtmlReport(HtmlReport.java:102)
	at com.occamlab.te.spi.util.HtmlReport.getHtmlResultZip(HtmlReport.java:62)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.getResultsFile(TestNGExecutor.java:172)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:140)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)
Caused by: java.io.FileNotFoundException: /home/stenger/testng/e9b58970-67d6-4b70-970d-281b649ec403/earl-results.rdf (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:371)
	... 9 more
---------
java.io.FileNotFoundException: /home/stenger/testng/e9b58970-67d6-4b70-970d-281b649ec403/earl-results.rdf (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:371)
	at net.sf.saxon.event.Sender.send(Sender.java:185)
	at net.sf.saxon.event.Sender.send(Sender.java:49)
	at net.sf.saxon.Controller.transform(Controller.java:1550)
	at com.occamlab.te.spi.util.HtmlReport.earlHtmlReport(HtmlReport.java:102)
	at com.occamlab.te.spi.util.HtmlReport.getHtmlResultZip(HtmlReport.java:62)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.getResultsFile(TestNGExecutor.java:172)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:140)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)

Exception in thread "main" java.lang.RuntimeException: net.sf.saxon.trans.XPathException: java.io.FileNotFoundException: /home/stenger/testng/e9b58970-67d6-4b70-970d-281b649ec403/earl-results.rdf (Datei oder Verzeichnis nicht gefunden)
	at com.occamlab.te.spi.util.HtmlReport.earlHtmlReport(HtmlReport.java:108)
	at com.occamlab.te.spi.util.HtmlReport.getHtmlResultZip(HtmlReport.java:62)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.getResultsFile(TestNGExecutor.java:172)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:140)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)
Caused by: net.sf.saxon.trans.XPathException: java.io.FileNotFoundException: /home/stenger/testng/e9b58970-67d6-4b70-970d-281b649ec403/earl-results.rdf (Datei oder Verzeichnis nicht gefunden)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:384)
	at net.sf.saxon.event.Sender.send(Sender.java:185)
	at net.sf.saxon.event.Sender.send(Sender.java:49)
	at net.sf.saxon.Controller.transform(Controller.java:1550)
	at com.occamlab.te.spi.util.HtmlReport.earlHtmlReport(HtmlReport.java:102)
	... 5 more
Caused by: java.io.FileNotFoundException: /home/stenger/testng/e9b58970-67d6-4b70-970d-281b649ec403/earl-results.rdf (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:371)
	... 9 more
```

Can you please describe the workflow how you executed the jar?

**Comment by bpross-52n** [comment]
@dstenger I can reproduce the errors using linux. I will investigate this.

**Comment by bpross-52n** [comment]
@dstenger The problem is, that no config.xml is available. The config.xml can be found in the file ets-wfs20-1.37-SNAPSHOT-ctl.zip under /wfs/2.0.0/. If you put the file in /home/stenger/teamengine/, the generation of the tests should work again. Let me know if this is feasible for you.

**Comment by dstenger** [comment]
@bpross-52n Why does this error not occur with Windows? What is the difference between different operating systems? At least, the documentation shall be updated regarding this.

**Comment by bpross-52n** [comment]
@dstenger It is independent of the operating system. On my Windows machine, the config.xml was already in place. On the fresh Linux machine that I used for testing, the config.xml was not available, thus the error happened. I hope this clarifies it.

**Comment by dstenger** [comment]
@bpross-52n 
Thank you! Your proposed workflow is working and the HTML report is generated.
However, the log output of the command does not point to the directory anymore (e.g. `Test results: file:/home/stenger/testng/c3b6646e-57c5-4e9d-8351-0dc13e7c5af2/testng-results.xml`).
I propose to keep this pull request on hold until we have a solution which is working smoothly (requires changes in TEAM Engine itself).

@jyrkka Does this workflow solve you problems? Do you have any additional questions?

**Comment by jyrkka** [comment]
@dstenger I don't have any additional questions.
