### ISSUE TITLE
Jersey doesn't accept "text/xml; subtype=gml/3.2" mime type

### ISSUE THREAD

**Issue by nmco** [opengeospatial/ets-wfs20#63]
Media type ``text/xml; subtype=gml/3.2`` seems to not be a valid media type (slash not allowed in the media types parameters):
- http://jersey.576304.n2.nabble.com/Media-type-parse-error-td6445421.html
- http://www.ogcnetwork.net/node/1704

When Jersey tries to handle something with media type ``text/xml; subtype=gml/3.2`` the following exception is throw:

```
Error parsing media type 'text/xml; subtype=gml/3.2'
java.lang.IllegalArgumentException: Error parsing media type 'text/xml; subtype=gml/3.2'
	at com.sun.jersey.core.impl.provider.header.MediaTypeProvider.fromString(MediaTypeProvider.java:79)
	at com.sun.jersey.core.impl.provider.header.MediaTypeProvider.fromString(MediaTypeProvider.java:53)
	at javax.ws.rs.core.MediaType.valueOf(MediaType.java:119)
	at com.sun.jersey.api.client.ClientResponse.getType(ClientResponse.java:695)
	at org.opengis.cite.iso19142.util.WFSClient.retrieveXMLResponseEntity(WFSClient.java:528)
	at org.opengis.cite.iso19142.util.WFSClient.getFeatureByType(WFSClient.java:179)
	at org.opengis.cite.iso19142.util.DataSampler.acquireFeatureData(DataSampler.java:238)
	at org.opengis.cite.iso19142.SuitePreconditions.dataAreAvailable(SuitePreconditions.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:123)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:141)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.text.ParseException: Expected separator ';' instead of '/'
	at com.sun.jersey.core.header.reader.HttpHeaderReader.nextSeparator(HttpHeaderReader.java:121)
	at com.sun.jersey.core.header.reader.HttpHeaderReader.readParameters(HttpHeaderReader.java:248)
	at com.sun.jersey.core.header.reader.HttpHeaderReader.readParameters(HttpHeaderReader.java:241)
	at com.sun.jersey.core.impl.provider.header.MediaTypeProvider.valueOf(MediaTypeProvider.java:97)
	at com.sun.jersey.core.impl.provider.header.MediaTypeProvider.fromString(MediaTypeProvider.java:77)
	... 36 more
```
WFS 2.0.0 (and 2.0.2) seems indeed to mandate media type ``text/xml; subtype=gml/3.2``, did I misunderstood something here ?

**Comment by nmco** [comment]
After re-checking the WFS 2.0 specification; in my understanding the mime type mandated by WFS 2.0 specification is ``application/gml+xml; version=3.2`` and not ``application/xml; subtype=gml/3.2`. 

Mime type ``application/gml+xml; version=3.2`` is also the one used by the reference implementation (Deegree). 

Some examples in WFS 2.0 specification are using ``application/xml; subtype=gml/3.2`` that's probably were the misunderstanding comes from.

**Comment by rjmartell** [comment]
Note that the solidus character ('/') is reserved in a media type parameter and must be escaped; this is the source of the parse exception. However, the subtype param is no longer used.
